/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_commsinfo_2eproto__INCLUDED
#define PROTOBUF_C_commsinfo_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Commsinfo Commsinfo;


/* --- enums --- */


/* --- messages --- */

struct  _Commsinfo
{
  ProtobufCMessage base;
  char *ip;
  double load;
  int32_t nop;
};
#define COMMSINFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&commsinfo__descriptor) \
    , NULL, 0, 0 }


/* Commsinfo methods */
void   commsinfo__init
                     (Commsinfo         *message);
size_t commsinfo__get_packed_size
                     (const Commsinfo   *message);
size_t commsinfo__pack
                     (const Commsinfo   *message,
                      uint8_t             *out);
size_t commsinfo__pack_to_buffer
                     (const Commsinfo   *message,
                      ProtobufCBuffer     *buffer);
Commsinfo *
       commsinfo__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   commsinfo__free_unpacked
                     (Commsinfo *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Commsinfo_Closure)
                 (const Commsinfo *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor commsinfo__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_commsinfo_2eproto__INCLUDED */
