/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "commsinfo.pb-c.h"
void   commsinfo__init
                     (Commsinfo         *message)
{
  static Commsinfo init_value = COMMSINFO__INIT;
  *message = init_value;
}
size_t commsinfo__get_packed_size
                     (const Commsinfo *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &commsinfo__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t commsinfo__pack
                     (const Commsinfo *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &commsinfo__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t commsinfo__pack_to_buffer
                     (const Commsinfo *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &commsinfo__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Commsinfo *
       commsinfo__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Commsinfo *)
     protobuf_c_message_unpack (&commsinfo__descriptor,
                                allocator, len, data);
}
void   commsinfo__free_unpacked
                     (Commsinfo *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &commsinfo__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor commsinfo__field_descriptors[3] =
{
  {
    "ip",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Commsinfo, ip),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "load",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Commsinfo, load),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nop",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Commsinfo, nop),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned commsinfo__field_indices_by_name[] = {
  0,   /* field[0] = ip */
  1,   /* field[1] = load */
  2,   /* field[2] = nop */
};
static const ProtobufCIntRange commsinfo__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor commsinfo__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Commsinfo",
  "Commsinfo",
  "Commsinfo",
  "",
  sizeof(Commsinfo),
  3,
  commsinfo__field_descriptors,
  commsinfo__field_indices_by_name,
  1,  commsinfo__number_ranges,
  (ProtobufCMessageInit) commsinfo__init,
  NULL,NULL,NULL    /* reserved[123] */
};
