/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "info.pb-c.h"
void   nodeinfo__init
                     (Nodeinfo         *message)
{
  static Nodeinfo init_value = NODEINFO__INIT;
  *message = init_value;
}
size_t nodeinfo__get_packed_size
                     (const Nodeinfo *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nodeinfo__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nodeinfo__pack
                     (const Nodeinfo *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nodeinfo__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nodeinfo__pack_to_buffer
                     (const Nodeinfo *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nodeinfo__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nodeinfo *
       nodeinfo__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nodeinfo *)
     protobuf_c_message_unpack (&nodeinfo__descriptor,
                                allocator, len, data);
}
void   nodeinfo__free_unpacked
                     (Nodeinfo *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nodeinfo__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor nodeinfo__field_descriptors[6] =
{
  {
    "np",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nodeinfo, np),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "npm",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nodeinfo, npm),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "npa",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nodeinfo, npa),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "load",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nodeinfo, load),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uthresh",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nodeinfo, uthresh),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lthresh",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nodeinfo, lthresh),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nodeinfo__field_indices_by_name[] = {
  3,   /* field[3] = load */
  5,   /* field[5] = lthresh */
  0,   /* field[0] = np */
  2,   /* field[2] = npa */
  1,   /* field[1] = npm */
  4,   /* field[4] = uthresh */
};
static const ProtobufCIntRange nodeinfo__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor nodeinfo__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nodeinfo",
  "Nodeinfo",
  "Nodeinfo",
  "",
  sizeof(Nodeinfo),
  6,
  nodeinfo__field_descriptors,
  nodeinfo__field_indices_by_name,
  1,  nodeinfo__number_ranges,
  (ProtobufCMessageInit) nodeinfo__init,
  NULL,NULL,NULL    /* reserved[123] */
};
